############################################
### Base image ###
############################################
ARG RUBY_VERSION=3.4.2

# cross-compilation: expose BuildKit platform args for FROM
ARG BUILDPLATFORM
ARG TARGETPLATFORM
FROM --platform=$BUILDPLATFORM ruby:$RUBY_VERSION-slim-bookworm as base

LABEL author="DCHBX"

ENV USERNAME=mitc

ARG DEBIAN_FRONTEND=noninteractive

ARG BUNDLER_VERSION=2.4.19

# Must be set as ENV variable to overrride the default
ENV BUNDLER_VERSION=$BUNDLER_VERSION

RUN apt-get update -qq && \
    apt-get install -yq --no-install-recommends \
      curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
    && truncate -s 0 /var/log/*log

ARG NODE_MAJOR=20

# Add NodeJS to sources list
RUN curl -sL https://deb.nodesource.com/setup_$NODE_MAJOR.x | bash -

RUN apt-get update \
    && apt-get -yq dist-upgrade \
    && apt-get install -y \
      fontconfig \
      libffi-dev \
      libsodium23 \
      libxext6 \
      libxrender1 \
      libyaml-cpp-dev \
      nodejs \
      default-jre \
      openssl \
      ruby-dalli \
      sshpass \
      unzip \
      zip \
      zlib1g \
      libyaml-dev \
      libjemalloc2 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
    && truncate -s 0 /var/log/*log

# Configure bundler and PATH, install bundler version
ENV GEM_HOME=/usr/local/bundle
ENV BUNDLE_PATH=$GEM_HOME
ENV BUNDLE_APP_CONFIG=$BUNDLE_PATH
ENV BUNDLE_BIN=/usr/local/bin
ENV BUNDLE_JOBS=4
ENV BUNDLE_RETRY=3

ENV LANG=C.UTF-8

ENV HOME=/mitc

ENV PATH=$HOME/bin:$BUNDLE_BIN:$GEM_HOME/gems/bin:$PATH

# RUN gem update --system
RUN rm -f /usr/local/bin/ruby/gems/*/specifications/default/bundler-*.gemspec
RUN gem install bundler -v $BUNDLER_VERSION

RUN groupadd --gid 1001 $USERNAME \
  && useradd --uid 1001 --gid $USERNAME --shell /bin/bash --create-home $USERNAME

RUN mkdir $HOME \
  && chown -R $USERNAME:$USERNAME $HOME

# Configure app home directory
WORKDIR $HOME

ENV RAILS_ENV=production
ENV NODE_ENV=production

###############################################################################
###       Builder. Adds node and Yarn. Not necessary in production.         ###
###############################################################################

FROM base as builder

ARG DEBIAN_FRONTEND=noninteractive

# Add Yarn to the sources list
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
  && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

# Install Nodejs & Yarn
RUN apt-get update -qq \
  && apt-get install -yq --no-install-recommends \
    build-essential \
    git \
    libpq-dev \
    yarn \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
  && truncate -s 0 /var/log/*log

########################################################
###          Node and Bundle for production          ###
########################################################

FROM builder as prod_gems_and_assets

ARG DEBIAN_FRONTEND=noninteractive

ARG HOSTNAME=localhost

COPY --chown=$USERNAME:$USERNAME package.json $HOME/
COPY --chown=$USERNAME:$USERNAME yarn.lock $HOME/

RUN yarn install \
  && (rm -rf /tmp/* || true)

COPY --chown=$USERNAME:$USERNAME ./Gemfile $HOME/Gemfile
COPY --chown=$USERNAME:$USERNAME ./Gemfile.lock $HOME/Gemfile.lock

RUN apt-get update -qq \
  && apt-get install -yq --no-install-recommends \
  shared-mime-info \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
  && truncate -s 0 /var/log/*log

RUN bundle config set --local without 'development test' \
  && bundle install

COPY --chown=$USERNAME:$USERNAME . $HOME

RUN bundle exec rake assets:precompile \
  && yarn cache clean \
  && (rm -rf /tmp/* || true) \
  # Cleanup
  && rm -rf $BUNDLE_PATH/*.gem \
  && find $BUNDLE_PATH/ruby -name "*.c" -delete \
  && find $BUNDLE_PATH/ruby -name "*.o" -delete \
  && find $BUNDLE_PATH/ruby -name ".git"  -type d -prune -execdir rm -rf {} +

# https://github.com/rubygems/rubygems/issues/3225
RUN rm -rf $GEM_HOME/bundle/ruby/*/cache

FROM base as deploy

# Copy prebuilt gems
COPY --chown=$USERNAME:$USERNAME --from=prod_gems_and_assets $BUNDLE_PATH $BUNDLE_PATH

# Copy all app code again (sans gems, node_modules, assets)
COPY --chown=$USERNAME:$USERNAME . $HOME

# Copy prebuilt assets
COPY --chown=$USERNAME:$USERNAME --from=prod_gems_and_assets $HOME/public $HOME/public

USER $USERNAME

ENTRYPOINT ["bin/docker-entrypoint"]
